### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by m2cci-VGU** [keenondrums/class-logger#3]
Hi, great job for this repo that has saved me from many headaches.

Like the title says, I used @Log() for a method that returns a promise, and when encountering a reject, I get the Unhandled promise rejection warning.
Now, I did not dive into your code, and I'm not an expert, but your examples do not cover this usecase so I thought I'd post an issue.

steps to reproduce: decorate a rejected promise
typescript: 3.1.6
class-logger: 1.1.0

Do you know about this problem / have any workaround / know if I'm looking the wrong way ?

Thanks in advance

**Comment by keenondrums** [comment]
@m2cci-VGU thank you for the report! The issue should be fixed in 1.2.0. I'll update [the demo](https://stackblitz.com/edit/class-logger-demo-basic) as soon as stackblitz invalidates its cache.

**Comment by keenondrums** [comment]
[The demo](https://stackblitz.com/edit/class-logger-demo-basic) is updated. You can see now there's no unhandled promise rejection present in the console.
